server:
  port: 8082

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/medBlog
      auto-index-creation: true
    #elasticsearch:

graphql:
  spqr:
    gui.enabled: true

